version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

formatters:
  enable:
    - gofmt

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - fatcontext
    - ginkgolinter
    - goconst
    - gocritic
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nakedret
    - nilnil
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - unparam
    - unused
    - unconvert
  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - linters: [revive]
        text: "dot-imports"
        path: "_test\\.go"
  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
