# ------------------------------------------------------------------------------
# P/D (Prefill/Decode) Development Environment
#
# Deploys the full dev stack with separate prefill and decode deployments.
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../components/vllm-prefill/
- ../../../components/vllm-decode/

patches:
- path: patch-decode.yaml

components:
- ../../../components/overlays/simulator/
